parquet:
  catalog: edm_pilot
  source_schema: source
  target_schema: target
  volume: edm_pilot_vol
  source_folder: raw
  target_folder: ddl
  stage_folder: stage
  control_table: batch_file_control
  target_tables: 
    - patient_ins: 
        template_file: /Volumes/edm_pilot/source/edm_pilot_vol/raw/patient_ins.AVERA_snappy.parquet
        primary_key: patient_sk
        not_null_fields: 
          - patient_sk
          - patient_bk
          - record_insert_timestamp
          - record_insert_id
          - record_update_timestamp
          - record_update_id
          - job_run_id
          - active_patient_ind
          - vendor_code
          - data_source_code
          - client_code
          - medical_record_number
          - birth_datetime
          - administrative_sex_code
          - source_update_timestamp
        foreign_keys:
          - name: fk1
            reference_table: practitioner
            reference_key: practitioner_sk

