clinical:
  ddl_path: emr_ddl_clinical/clinical
  folders:
    - table
    - view
    - index
    - data
  source_schema: clinical
dbr:
  db_catalog: dbr_ssa_clinical
  db_schema: clinical_bronze
  volume: clinical_raw/clinical_data_volume
  mode: overwrite
  target_folder: dbr_ddl_clinical
patient:
  patient_table: patient
  patient_table_path: data/patient/patient.txt
