clinical:
  ddl_path: /Volumes/clinical/clinical_raw/clinical_data_volume/emr_ddl_clinical/clinical
  folders:
    - table
    - view
    - index
    - data
  source_schema: clinical
dbr:
  db_catalog: clinical
  db_schema: clinical_bronze
  mode: overwrite
  target_folder: /Volumes/clinical/clinical_raw/clinical_data_volume/dbr_ddl_clinical
